---
jira_tar_archive: "atlassian-jira-{{ jira_version }}.tar.gz"

jira_download_url: "http://www.atlassian.com/software/jira/downloads/binary/{{ jira_tar_archive }}"

jira_groupname: jira

jira_username: jira

jira_install_dir: /opt/jira

jira_home_dir: /opt/jira-home


