---
- hosts: localhost
  user: root

  vars:
    DB_SERVICE_ADDRESS: "{{ lookup('env','DB_SERVICE_ADDRESS') }}"
    jira_db_name: "{{ lookup('env','APP_DB_NAME') }}"
    jira_db_username: "{{ lookup('env','APP_DB_USERNAME') }}"
    jira_db_password: "{{ lookup('env','APP_DB_PASSWORD') }}"
    jira_tcp_port: "{{ lookup('env','APP_TCP_PORT') }}"
    jira_test_http_endpoint: "{{ lookup('env','APP_TEST_HTTP_ENDPOINT') }}"
    jira_test_http_status_code: "{{ lookup('env','APP_TEST_HTTP_STATUS_CODE') }}"
    jira_test_string: "{{ lookup('env','APP_TEST_STRING') }}"
    jira_version: "{{ lookup('env','APP_VERSION') }}"

  roles:
    - jira
