---
# TODO this is very similar to test.yml
- hosts: localhost
  user: root

  vars:
    DB_SERVICE_ADDRESS: "{{ lookup('env','DB_SERVICE_ADDRESS') }}"
    jira_db_name: "{{ lookup('env','APP_DB_NAME') }}"
    jira_db_username: "{{ lookup('env','APP_DB_USERNAME') }}"
    jira_db_password: "{{ lookup('env','APP_DB_PASSWORD') }}"

  tasks:
    - include_vars: jira/defaults/main.yml

    - include: jira/tasks/deploy.yml

