---
- hosts: localhost
  user: vagrant
  sudo: yes
  sudo_user: root

  vars:
    postgresql_databases: 
      - name: 9d617b7
        hstore: no
    postgresql_users:
      - name: 9d617b7
        pass: 9d617b7
        encrypted: no
    postgresql_user_privileges:
      - name: 9d617b7
        db: 9d617b7
        priv: "ALL"
    postgresql_pg_hba_default:
      - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: '{{ socket_postgresql_default_auth_method }}', comment: '' }
      - { type: local, database: all, user: all, address: '', method: '{{ socket_postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
      - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ ipv4_postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
      - { type: host, database: all, user: all, address: '::1/128', method: '{{ ipv6_postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }
      - { type: host,  database: all, user: all, address: '0.0.0.0/0', method: '{{ ipv4_postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
    postgresql_listen_addresses:
      - 0.0.0.0 

  roles:
    - { role: patrik.uytterhoeven.PostgreSQL-For-RHEL6x,
        pgsql_repo: 'http://yum.postgresql.org/9.3/redhat/rhel-7-x86_64/pgdg-redhat93-9.3-1.noarch.rpm',
        postgresql_version: 9.3,
        postgresql_encoding: 'UTF-8',
        postgresql_locale: 'en_US.UTF-8' } 
